sources:
  - title: Tech Dirt
    link: https://www.techdirt.com/feed
    category: Tech
    s_type: RSS
  - title: Crossplay
    link: https://patrickklepek.substack.com/feed
    category: Games
    s_type: RSS
  - title: Clockwork Worlds
    link: https://www.clockworkworlds.com/rss/
    category: Games
    s_type: RSS
  - title: Remap Subreddit
    link: https://www.reddit.com/r/WaypointVICE/.rss
    category: Games
    s_type: Atom
  - title: Formula 1 Subreddit
    link: https://www.reddit.com/r/formula1/.rss
    category: Racing
    s_type: Atom
  - title: Scala Subreddit
    link: https://www.reddit.com/r/scala/.rss
    category: Code
    s_type: Atom
  - title: Petr Zapletal
    link: https://medium.com/feed/@petr-zapletal
    category: Code
    s_type: RSS
  - title: Remap Radio
    link: https://remapradio.com/articles/rss/
    category: Games
    s_type: RSS
  - title: Aftermath
    link: https://aftermath.site/rss
    category: Games
    s_type: RSS
  - title: 404 Media
    link: https://www.404media.co/rss/
    category: Tech
    s_type: RSS
  - title: Wired
    link: https://www.wired.com/feed/rss
    s_type: RSS
    category: Tech
  - title: Knapp Arcade
    link: https://knapparcade.com/api/rss
    s_type: RSS
    category: Pinball
